//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanVLXD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONNHAPHANG
    {
        public HOADONNHAPHANG()
        {
            this.PHIEUNHAPs = new HashSet<PHIEUNHAP>();
        }
    
        public string MaHDN { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string MaNCC { get; set; }
        public string MaQL { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual ICollection<PHIEUNHAP> PHIEUNHAPs { get; set; }
    }
}
