//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanVLXD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.PhieuXuats = new HashSet<PhieuXuat>();
        }
    
        public int KhachHangID { get; set; }
        public Nullable<int> TaiKhoanID { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual ICollection<PhieuXuat> PhieuXuats { get; set; }
    }
}
