//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanVLXD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuVucKho
    {
        public KhuVucKho()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int KhuVucKhoID { get; set; }
        public string TenKhuVuc { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
