//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanVLXD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            this.ChiTietNhaps = new HashSet<ChiTietNhap>();
        }
    
        public int PhieuNhapID { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public Nullable<int> NhaCungCapID { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<ChiTietNhap> ChiTietNhaps { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
