//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanVLXD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        public PhieuXuat()
        {
            this.ChiTietXuats = new HashSet<ChiTietXuat>();
        }
    
        public int PhieuXuatID { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<ChiTietXuat> ChiTietXuats { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
