//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanVLXD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietNhaps = new HashSet<ChiTietNhap>();
            this.ChiTietXuats = new HashSet<ChiTietXuat>();
            this.ThuocTinhs = new HashSet<ThuocTinh>();
        }
    
        public int SanPhamID { get; set; }
        public string TenSanPham { get; set; }
        public string MoTa { get; set; }
        public decimal Gia { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string DonViTinh { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> NhaCungCapID { get; set; }
        public Nullable<int> KhuVucKhoID { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual ICollection<ChiTietNhap> ChiTietNhaps { get; set; }
        public virtual ICollection<ChiTietXuat> ChiTietXuats { get; set; }
        public virtual KhuVucKho KhuVucKho { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual ICollection<ThuocTinh> ThuocTinhs { get; set; }
    }
}
