//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanVLXD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuocTinh
    {
        public int ThuocTinhID { get; set; }
        public string TenThuocTinh { get; set; }
        public string GiaTri { get; set; }
        public Nullable<int> SanPhamID { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
