<?xml version="1.0" encoding="utf-8"?><Database Name="VLXD_DB" Class="VLXD_DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.CTHOADON" Member="CTHOADONs">
    <Type Name="CTHOADON">
      <Column Name="MaHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="SANPHAM_CTHOADON" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
      <Association Name="HOADON_CTHOADON" Member="HOADON" ThisKey="MaHD" OtherKey="MaHD" Type="HOADON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MaSP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="SANPHAM_CTHOADON" Member="CTHOADONs" ThisKey="MaSP" OtherKey="MaSP" Type="CTHOADON" />
      <Association Name="SANPHAM_PHIEUNHAP" Member="PHIEUNHAPs" ThisKey="MaSP" OtherKey="MaSP" Type="PHIEUNHAP" />
      <Association Name="NHACUNGCAP_SANPHAM" Member="NHACUNGCAP" ThisKey="MaNCC" OtherKey="MaNCC" Type="NHACUNGCAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MaHD" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PhuongThucTT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MaKH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaQL" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="HOADON_CTHOADON" Member="CTHOADONs" ThisKey="MaHD" OtherKey="MaHD" Type="CTHOADON" />
      <Association Name="NGUOIDUNG_HOADON" Member="NGUOIDUNG" ThisKey="MaKH" OtherKey="MaUser" Type="NGUOIDUNG" IsForeignKey="true" />
      <Association Name="NGUOIDUNG_HOADON1" Member="NGUOIDUNG1" ThisKey="MaQL" OtherKey="MaUser" Type="NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONNHAPHANG" Member="HOADONNHAPHANGs">
    <Type Name="HOADONNHAPHANG">
      <Column Name="MaHDN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaQL" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="HOADONNHAPHANG_PHIEUNHAP" Member="PHIEUNHAPs" ThisKey="MaHDN" OtherKey="MaHDN" Type="PHIEUNHAP" />
      <Association Name="NGUOIDUNG_HOADONNHAPHANG" Member="NGUOIDUNG" ThisKey="MaQL" OtherKey="MaUser" Type="NGUOIDUNG" IsForeignKey="true" />
      <Association Name="NHACUNGCAP_HOADONNHAPHANG" Member="NHACUNGCAP" ThisKey="MaNCC" OtherKey="MaNCC" Type="NHACUNGCAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNG" Member="NGUOIDUNGs">
    <Type Name="NGUOIDUNG">
      <Column Name="MaUser" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNguoiDung" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NGUOIDUNG_HOADON" Member="HOADONs" ThisKey="MaUser" OtherKey="MaKH" Type="HOADON" />
      <Association Name="NGUOIDUNG_HOADON1" Member="HOADONs1" ThisKey="MaUser" OtherKey="MaQL" Type="HOADON" />
      <Association Name="NGUOIDUNG_HOADONNHAPHANG" Member="HOADONNHAPHANGs" ThisKey="MaUser" OtherKey="MaQL" Type="HOADONNHAPHANG" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="MaNCC" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NHACUNGCAP_SANPHAM" Member="SANPHAMs" ThisKey="MaNCC" OtherKey="MaNCC" Type="SANPHAM" />
      <Association Name="NHACUNGCAP_HOADONNHAPHANG" Member="HOADONNHAPHANGs" ThisKey="MaNCC" OtherKey="MaNCC" Type="HOADONNHAPHANG" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAP" Member="PHIEUNHAPs">
    <Type Name="PHIEUNHAP">
      <Column Name="MaHDN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGiaNhap" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="HOADONNHAPHANG_PHIEUNHAP" Member="HOADONNHAPHANG" ThisKey="MaHDN" OtherKey="MaHDN" Type="HOADONNHAPHANG" IsForeignKey="true" />
      <Association Name="SANPHAM_PHIEUNHAP" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
</Database>